fix(google-maps-provider): quick fix google maps check
ubilabs/google-maps-react-hooks pull request #121
Opened 2022-11-10 17:53 UTC by BiniCodes

So this was sometimes occuring:

![image](https://user-images.githubusercontent.com/39244966/201169592-6767bd9d-cfa3-43b0-898b-315295850182.png)

I think you wanted to handle this via `isLoadingAPI`, no? @plumdumpling 
This fixes it for now, but we got to recheck the loading of the script tag as the state of `isLoadingAPI` is false sometimes when loading the script and I think this is the main problem.

2022-11-10 17:54 UTC, BiniCodes commented
Tests should work after merging: https://github.com/ubilabs/google-maps-react-hooks/pull/120

2022-11-11 07:56 UTC, plumdumpling requested changes
> I think you wanted to handle this via isLoadingAPI, no? @plumdumpling

Yes, the `isLoadingAPI` state should do this. Please let's see what's wrong with it and fix it there.

2022-11-15 10:29 UTC, BiniCodes commented
> > I think you wanted to handle this via isLoadingAPI, no? @plumdumpling
> 
> Yes, the `isLoadingAPI` state should do this. Please let's see what's wrong with it and fix it there.

Added a comment above the code for the check as I currently do not see another way :)

2022-11-15 10:59 UTC, plumdumpling approved these changes

2022-11-15 10:59 UTC, plumdumpling commented on library/src/google-maps-provider.tsx
> +    // Check for google.maps is needed because of Hot Module loading
```suggestion
    // Check for google.maps is needed because of Hot Module Replacement
```

2022-11-15 11:35 UTC, BiniCodes commented on library/src/google-maps-provider.tsx
> +    // Check for google.maps is needed because of Hot Module loading
I was thinking about it :D

2022-11-15 13:43 UTC, merged